// Loaded JavaScripts:
// https://unpkg.com/react@16.13.1/umd/react.production.min.js
// https://unpkg.com/react-markdown@4.3.1/umd/react-markdown.js

// Reference ns as ReactMarkdown
/**********************************************************************
 * Extern for ReactMarkdown
 * Generated by http://jmmk.github.io/javascript-externs-generator
 **********************************************************************/
var ReactMarkdown = {
  "defaultProps": {
    "astPlugins": {},
    "escapeHtml": {},
    "parserOptions": {},
    "plugins": {},
    "rawSourcePos": {},
    "renderers": {},
    "skipHtml": {},
    "sourcePos": {},
    "transformLinkUri": function () {}
  },
  "propTypes": {
    "allowNode": {
      "isRequired": function () {}
    },
    "allowedTypes": {
      "isRequired": function () {}
    },
    "astPlugins": {
      "isRequired": function () {}
    },
    "children": {
      "isRequired": function () {}
    },
    "className": {
      "isRequired": function () {}
    },
    "disallowedTypes": {
      "isRequired": function () {}
    },
    "escapeHtml": {
      "isRequired": function () {}
    },
    "linkTarget": {
      "isRequired": function () {}
    },
    "parserOptions": {
      "isRequired": function () {}
    },
    "plugins": {
      "isRequired": function () {}
    },
    "rawSourcePos": {
      "isRequired": function () {}
    },
    "renderers": {
      "isRequired": function () {}
    },
    "skipHtml": {
      "isRequired": function () {}
    },
    "source": {
      "isRequired": function () {}
    },
    "sourcePos": {
      "isRequired": function () {}
    },
    "transformImageUri": {
      "isRequired": function () {}
    },
    "transformLinkUri": {
      "isRequired": function () {}
    },
    "unwrapDisallowed": {
      "isRequired": function () {}
    }
  },
  "renderers": {
    "blockquote": {},
    "break": {},
    "code": function () {},
    "definition": function () {},
    "delete": {},
    "emphasis": {},
    "heading": function () {},
    "html": function () {},
    "image": {},
    "imageReference": {},
    "inlineCode": function () {},
    "link": {},
    "linkReference": {},
    "list": function () {},
    "listItem": function () {},
    "paragraph": {},
    "parsedHtml": function () {},
    "root": function () {},
    "strong": {},
    "table": function () {},
    "tableBody": function () {},
    "tableCell": function () {},
    "tableHead": function () {},
    "tableRow": function () {},
    "text": function () {},
    "thematicBreak": {},
    "virtualHtml": function () {}
  },
  "types": {},
  "uriTransformer": function () {}
};
/**********************************************************************
 * End Generated Extern for ReactMarkdown
/**********************************************************************/
